// <auto-generated />
using CENProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CENProject.Migrations.Reviews
{
    [DbContext(typeof(ReviewsContext))]
    partial class ReviewsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CENProject.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AOT")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("CC")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CLA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("CLT")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("CoMM")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("CoPW")
                        .HasColumnType("decimal(3,2)");

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<decimal>("Mechanics")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("OR")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("ORC")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OoP")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("Originality")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("PIiT")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("PaperID")
                        .HasColumnType("int");

                    b.Property<string>("PfOPC")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewerID")
                        .HasColumnType("int");

                    b.Property<decimal>("SE")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("SfP")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("SoC")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("TQ")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("ToT")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("WDC")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReviewID");

                    b.ToTable("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
