// <auto-generated />
using CENProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CENProject.Migrations.Reviewers
{
    [DbContext(typeof(ReviewersContext))]
    partial class ReviewersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CENProject.Models.Reviewer", b =>
                {
                    b.Property<int>("ReviewerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AI")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AoA")
                        .HasColumnType("bit");

                    b.Property<bool>("Applications")
                        .HasColumnType("bit");

                    b.Property<bool>("Architecture")
                        .HasColumnType("bit");

                    b.Property<bool>("CE")
                        .HasColumnType("bit");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Curriculum")
                        .HasColumnType("bit");

                    b.Property<bool>("DL")
                        .HasColumnType("bit");

                    b.Property<bool>("DS")
                        .HasColumnType("bit");

                    b.Property<bool>("DSS")
                        .HasColumnType("bit");

                    b.Property<bool>("Database")
                        .HasColumnType("bit");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ESI")
                        .HasColumnType("bit");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("FYC")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("GI")
                        .HasColumnType("bit");

                    b.Property<bool>("GIP")
                        .HasColumnType("bit");

                    b.Property<bool>("GW")
                        .HasColumnType("bit");

                    b.Property<bool>("HCI")
                        .HasColumnType("bit");

                    b.Property<bool>("LE")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Literacy")
                        .HasColumnType("bit");

                    b.Property<bool>("MIC")
                        .HasColumnType("bit");

                    b.Property<string>("MiddleInitial")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<bool>("Multimedia")
                        .HasColumnType("bit");

                    b.Property<bool>("NDC")
                        .HasColumnType("bit");

                    b.Property<bool>("NMC")
                        .HasColumnType("bit");

                    b.Property<string>("OD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("OOI")
                        .HasColumnType("bit");

                    b.Property<bool>("OS")
                        .HasColumnType("bit");

                    b.Property<bool>("Other")
                        .HasColumnType("bit");

                    b.Property<bool>("PL")
                        .HasColumnType("bit");

                    b.Property<bool>("PP")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("Pedagogy")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RA")
                        .HasColumnType("bit");

                    b.Property<bool>("Research")
                        .HasColumnType("bit");

                    b.Property<bool>("SAAD")
                        .HasColumnType("bit");

                    b.Property<bool>("SE")
                        .HasColumnType("bit");

                    b.Property<bool>("Security")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("UTITC")
                        .HasColumnType("bit");

                    b.Property<bool>("WAIP")
                        .HasColumnType("bit");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ReviewerID");

                    b.ToTable("Reviewer");
                });
#pragma warning restore 612, 618
        }
    }
}
