// <auto-generated />
using CENProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CENProject.Migrations.Papers
{
    [DbContext(typeof(PapersContext))]
    partial class PapersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CENProject.Models.Paper", b =>
                {
                    b.Property<int>("PaperID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AI")
                        .HasColumnType("bit");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<bool>("AoA")
                        .HasColumnType("bit");

                    b.Property<bool>("Applications")
                        .HasColumnType("bit");

                    b.Property<bool>("Architecture")
                        .HasColumnType("bit");

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<bool>("CE")
                        .HasColumnType("bit");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("Curriculum")
                        .HasColumnType("bit");

                    b.Property<bool>("DL")
                        .HasColumnType("bit");

                    b.Property<bool>("DS")
                        .HasColumnType("bit");

                    b.Property<bool>("DSS")
                        .HasColumnType("bit");

                    b.Property<bool>("Database")
                        .HasColumnType("bit");

                    b.Property<bool>("ESI")
                        .HasColumnType("bit");

                    b.Property<bool>("FYC")
                        .HasColumnType("bit");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FilenameOriginal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("GI")
                        .HasColumnType("bit");

                    b.Property<bool>("GIP")
                        .HasColumnType("bit");

                    b.Property<bool>("GW")
                        .HasColumnType("bit");

                    b.Property<bool>("HCI")
                        .HasColumnType("bit");

                    b.Property<bool>("LE")
                        .HasColumnType("bit");

                    b.Property<bool>("Literacy")
                        .HasColumnType("bit");

                    b.Property<bool>("MIC")
                        .HasColumnType("bit");

                    b.Property<bool>("Multimedia")
                        .HasColumnType("bit");

                    b.Property<bool>("NDC")
                        .HasColumnType("bit");

                    b.Property<bool>("NMC")
                        .HasColumnType("bit");

                    b.Property<string>("NotesToReviewers")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("OOI")
                        .HasColumnType("bit");

                    b.Property<bool>("OS")
                        .HasColumnType("bit");

                    b.Property<bool>("Other")
                        .HasColumnType("bit");

                    b.Property<bool>("PL")
                        .HasColumnType("bit");

                    b.Property<bool>("PP")
                        .HasColumnType("bit");

                    b.Property<bool>("Pedagogy")
                        .HasColumnType("bit");

                    b.Property<bool>("Research")
                        .HasColumnType("bit");

                    b.Property<bool>("SAAD")
                        .HasColumnType("bit");

                    b.Property<bool>("SE")
                        .HasColumnType("bit");

                    b.Property<bool>("Security")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("UTITC")
                        .HasColumnType("bit");

                    b.Property<bool>("WAIP")
                        .HasColumnType("bit");

                    b.HasKey("PaperID");

                    b.ToTable("Paper");
                });
#pragma warning restore 612, 618
        }
    }
}
